### ISSUE TITLE
overriding machine provider properties

### ISSUE THREAD

**Issue by badmutex** [futuresystems/virtual-cluster-libs#9]
Given something like:

``` yaml
machines:
  datanode:
    providers:
      chameleon:
        image: m1.xlarge
  ...
```

overriding the image for chameleon needs to be implemented
